import "./globals.css";
import BasicLayout from "@/layout/basic-layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BasicLayout>{children}</BasicLayout>
      </body>
    </html>
  );
}
