"use client";

import "./globals.css";

import Dropdown from "@/components/ui/dropdown/dropdown";
import DropdownContent from "@/components/ui/dropdown/dropdown-content";
import Button from "@/components/ui/button/button";
import Menu from "@/components/ui/menu/menu";
import SubMenu from "@/components/ui/menu/sub-menu";
import MenuItem from "@/components/ui/menu/menu-item";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-muted">
          <header className="h-12 bg-background border-b pl-10 pt-1">
            <Dropdown trigger="click" position="top">
              <Button>菜单</Button>
              <DropdownContent>
                <Menu>
                  <MenuItem>123</MenuItem>
                  <MenuItem>456</MenuItem>
                  <MenuItem>789</MenuItem>
                  <SubMenu title="123">
                    <MenuItem>123</MenuItem>
                    <MenuItem>456</MenuItem>
                    <SubMenu title="789">
                      <MenuItem>123</MenuItem>
                      <MenuItem>456</MenuItem>
                      <MenuItem>789</MenuItem>
                    </SubMenu>
                  </SubMenu>
                </Menu>
              </DropdownContent>
            </Dropdown>
          </header>
          <div className="flex">
            <aside className="bg-background"></aside>
            <div
              className="overflow-y-auto overflow-x-hidden flex-1"
              style={{ height: "calc(100vh - 3rem)" }}
            >
              <main>{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
