"use client";

import "./globals.css";

import Dropdown from "@/components/ui/dropdown/dropdown";
import DropdownContent from "@/components/ui/dropdown/dropdown-content";
import Button from "@/components/ui/button";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-muted">
          <header className="h-12 bg-background border-b">
            <Dropdown trigger="hover">
              <Button>菜单</Button>
              <DropdownContent>123</DropdownContent>
            </Dropdown>
          </header>
          <div className="flex">
            <aside className="bg-background"></aside>
            <div
              className="overflow-y-auto overflow-x-hidden flex-1"
              style={{ height: "calc(100vh - 3rem)" }}
            >
              <main>{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
